import type { ThemeColors } from '../types/theme.types';

const BRAND = {
  PRIMARY: '#111111',
  PRIMARY_LIGHT: '#2A2A2A',
  DANGER: '#7A7A7A',
  SUCCESS: '#4A4A4A',
  SUCCESS_STRONG: '#16a34a', // vert pour "Oui"
  DANGER_STRONG: '#dc2626', // rouge pour "Non"
} as const;

export const LIGHT_THEME: ThemeColors = {
  ...BRAND,
  TAB_ACTIVE: '#111111',
  TAB_INACTIVE: '#8A8A8F',
  TAB_BAR_BG: '#FFFFFF',
  TAB_BAR_BORDER: '#E4E4E7',
  HEADER_BG: '#FFFFFF',
  HEADER_TEXT: '#111111',
  BG_PRIMARY: '#FFFFFF',
  BG_SECONDARY: '#F7F7F8',
  BG_TERTIARY: '#EFEFF1',
  TEXT_PRIMARY: '#111111',
  TEXT_SECONDARY: '#6F6F75',
  TEXT_INVERSE: '#FFFFFF',
  SETTINGS_SECTION_BG: '#FFFFFF',
  SETTINGS_SEPARATOR: '#D2D2D7',
  SETTINGS_ICON_BG: '#F2F2F4',
  BORDER: '#E4E4E7',
};
