-- public.user.id n'avait ni default, ni identity, ni séquence : tout insert sans id
-- explicite (ex. createUser() côté CRM admin-desktop-app/lib/actions/users.ts) échouait
-- avec une violation not-null ("null value in column id"). Bug confirmé le 2026-08-19
-- en testant le provisioning auto (volet must_change_password).
-- Séquence calée juste au-dessus du max(id) existant (390) pour ne pas entrer en
-- collision avec les lignes déjà en base.
alter table public.user
  alter column id add generated by default as identity (restart with 391);
